Update frontend-testing.yml

diff --git a/.github/workflows/frontend-testing.yml b/.github/workflows/frontend-testing.yml
--- a/.github/workflows/frontend-testing.yml
+++ b/.github/workflows/frontend-testing.yml
@@ -66,10 +66,17 @@ jobs:
 
     - name: Wait for containers to be healthy
       run: |
-        docker-compose -f Frontend/docker-compose.integration.yml ps
-        until [ $(docker inspect --format='{{json .State.Health.Status}}' diploma-maker-test-backend) == '"healthy"' ]; do
-          echo "Waiting for backend to be healthy...";
-          sleep 10;
+        retries=0
+        max_retries=3
+        while [ $(docker inspect --format='{{json .State.Health.Status}}' diploma-maker-test-backend_1) != '"healthy"' ]; do
+          if [ $retries -ge $max_retries ]; then
+            echo "Backend failed to become healthy after $retries attempts."
+            docker logs diploma-maker-test-backend_1
+            exit 1
+          fi
+          echo "Waiting for backend to be healthy... Attempt: $((retries+1))"
+          retries=$((retries+1))
+          sleep 10
         done
 
     - name: Run Integration Tests
